# Application Setting
spring:
  application:
    name: momo

# Data Source Setting
  datasource:
    url: jdbc:mariadb://localhost:3306/momodb
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

# JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

# File Upload Setting
  servlet:
    multipart:
      enabled: true
      location: ${user.home}/upload/
      max-request-size: 30MB
      max-file-size: 30MB

  # Thymeleaf Setting
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: true

  # OAuth2 Social Login Setting
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope: profile_nickname,account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile,email

# kakao api
kakao:
  api:
    key: ${KAKAO_API_KEY}

  # Mail Setting
  mail:
    host: smtp.gmail.com
    port: 587
    username: dbwjd4689@gmail.com
    password: qidb dbjs qxpx mgrg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            protocols: TLSv1.2
        debug: true

# File Upload Setting
UploadPath: ${user.home}/upload/
#UploadPath: classpath:/assets/upload/ class path is readonly path

# Server Setting
server:
  port: 8080
  servlet:
    session:
      timeout: 30m

# Logging Level Setting
logging:
  level:
    root: warn
    org.springframework: info
    org.springframework.security: info
    com.momo: trace





